// example/src/components/FilterSelect.tsx
import React, { useState } from "react";
import classnames from "classnames";
import useSelect from "../hooks/useSelect";
import { DecoratedItem } from "use-dropdown";
import { itemMatchesFilter } from "../utils";
import {
  selectStyles,
  listBoxStyles,
  itemStyles,
  listBoxContainerStyles
} from "./Select";

type Item = {
  name: string;
  id: String;
};

interface IFilterableSelectProps {
  items: Array<Item>;
  autoTargetFirstItem?: boolean;
}

function FilteringSelect({
  items,
  autoTargetFirstItem
}: IFilterableSelectProps) {
  const [selected, setSelected] = useState<Item | null>(null);

  const {
    isOpen,
    decoratedItems,
    getItemProps,
    getListProps,
    getFilterInputProps,
    getSelectProps,
    isItemActive,
    isItemSelected,
    state
  } = useSelect({
    onSelectOption: setSelected,
    items,
    itemMatchesFilter,
    selected,
    autoTargetFirstItem
  });

  return (
    <div>
      <div
        {...getSelectProps()}
        className={classnames(selectStyles, {
          "border-blue-600 rounded-b-none": isOpen
        })}
      >
        {!!selected ? selected.name : ""}
      </div>
      <div className={classnames(listBoxContainerStyles, { hidden: !isOpen })}>
        <input
          {...getFilterInputProps()}
          className="outline-none"
          type="text"
          placeholder="Filter..."
        />
        <ul
          {...getListProps()}
          className={classnames(listBoxStyles, "relative")}
        >
          {decoratedItems.map((item: DecoratedItem<Item>, index: number) => (
            <li
              {...getItemProps(item)}
              key={item.id || index}
              className={classnames(itemStyles, {
                "bg-gray-200": isItemActive(item, state.context),
                "bg-gray-400": isItemSelected(item, selected)
              })}
            >
              {item.item.name}
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

export default FilteringSelect;

// vue-example/src/components/FilterSelect.vue
<template>
  <div>
    <div
      :class="selectClasses"
      @keydown="handleKeydownSelect"
      @click="handleClickSelect"
      tabindex="0"
    >
      {{ !!state.selected ? state.selected.name : "" }}
    </div>
    <ul ref="listRef" :class="listClasses" v-show="isOpen()">
      <li
        v-for="decoratedItem in state.decoratedItems"
        ref="itemsRef"
        :key="decoratedItem.id"
        :class="getItemClasses(decoratedItem)"
        @mousemove="() => handleMousemoveItem(decoratedItem)"
        @click="() => handleClickItem(decoratedItem)"
      >
        {{ decoratedItem.item.name }}
      </li>
    </ul>
  </div>
</template>

<script lang="ts">
export const selectStyles =
  "w-64 h-10 border border-gray-500 flex rounded-sm outline-none items-center p-2 focus:border-blue-600 cursor-pointer";
export const listBoxContainerStyles =
  "shadow-lg border border-gray-500 rounded-sm rounded-t-none outline-none absolute bg-white z-10 border-blue-600 cursor-pointer";
export const listBoxStyles = "w-64 h-48 overflow-y-auto cursor-pointer";
export const itemStyles = "px-2 py-1";
import { useMachine } from "@xstate/vue";
import { reactive, ref, onUpdated } from "@vue/composition-api";
import classnames from "classnames";
import {
  selectMachine,
  CLICK_TRIGGER,
  CLICK_ITEM,
  SET_ACTIVE_ITEM,
  KEY_DOWN_SELECT,
  UPDATE_DECORATED_ITEMS,
  UPDATE_LIST_ELEMENT,
  isItemActive,
  isItemSelected
} from "use-dropdown";

type Item = any;

export default {
  name: "Select",
  props: {
    items: Array
  },
  setup(props: any) {
    const itemsRef = ref(null);
    const state = reactive({
      selected: null,
      decoratedItems: props.items.map((item: any) => ({
        ref: null,
        item
      }))
    });

    const listRef = ref(null);

    function handleSelectOption(item: Item) {
      state.selected = item;
    }

    const { state: machineState, send } = useMachine(selectMachine, {
      context: {
        listElement: listRef.value as any,
        decoratedItems: state.decoratedItems,
        filteredDecoratedItems: state.decoratedItems,
        onSelectOption: handleSelectOption,
        selected: state.selected
      }
    });

    function getListClasses() {
      return `${listBoxContainerStyles} ${listBoxStyles}`;
    }

    onUpdated(() => {
      if (machineState.value.context.listElement !== listRef.value) {
        send({
          type: UPDATE_LIST_ELEMENT,
          listElement: listRef.value
        });
      }

      const refs = itemsRef?.value || [];
      const decoratedItemsWithRefs = state.decoratedItems.map(
        (item: any, index: number) => ({ ...item, ref: refs && refs[index] })
      );
      if (!machineState.value.context.decoratedItems[0].ref) {
        state.decoratedItems = decoratedItemsWithRefs;
        send({
          type: UPDATE_DECORATED_ITEMS,
          decoratedItems: decoratedItemsWithRefs
        });
      }
    });

    return {
      state,
      send,
      machineState,
      getListClasses,
      listRef,
      itemsRef
    };
  },
  data: function() {
    return {
      selectClasses: selectStyles,
      listClasses: `${listBoxContainerStyles} ${listBoxStyles}`
    };
  },
  methods: {
    handleKeydownSelect: function(e: KeyboardEvent) {
      this.send({ type: KEY_DOWN_SELECT, e });
    },

    handleClickSelect: function() {
      this.send(CLICK_TRIGGER);
    },

    handleClickItem: function({ item }) {
      this.send({ type: CLICK_ITEM, item });
    },

    handleMousemoveItem: function(decoratedItem) {
      this.send({ type: `${SET_ACTIVE_ITEM}`, decoratedItem });
    },

    isOpen: function() {
      return this.machineState.value === "open";
    },

    getItemClasses: function(decoratedItem) {
      const { context } = this.machineState;
      return classnames(itemStyles, {
        "bg-gray-200": isItemActive(decoratedItem, context),
        "bg-gray-400": isItemSelected(decoratedItem, this.state.selected)
      });
    }
  }
};
</script>
