// example/src/components/MultiSelect.tsx
import React, { useState, MouseEvent } from "react";
import classnames from "classnames";
import useSelect from "../hooks/useSelect";
import { itemStyles, listBoxStyles, listBoxContainerStyles } from "./Select";
import { DecoratedItem } from "use-dropdown";

export const closeIcon = (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
    <path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm1.41-1.41A8 8 0 1 0 15.66 4.34 8 8 0 0 0 4.34 15.66zm9.9-8.49L11.41 10l2.83 2.83-1.41 1.41L10 11.41l-2.83 2.83-1.41-1.41L8.59 10 5.76 7.17l1.41-1.41L10 8.59l2.83-2.83 1.41 1.41z" />
  </svg>
);

export const multiSelectStyles =
  "w-64 h-12 border border-gray-500 flex flex-wrap rounded-sm outline-none items-center p-2 focus:border-blue-600 cursor-pointer";

export const pillStyles =
  "flex items-center mr-2 border border-gray-500 rounded-md px-1";
export const pillCloseStyles =
  "h-3 w-3 fill-current text-blue-400 ml-2 hover:text-blue-600";

type Item = {
  name: string;
  id: string;
};

interface ISelectedItemProps {
  item: Item;
  onRemove(item: Item): any;
}

function SelectedItem({ item, onRemove }: ISelectedItemProps) {
  function handleClick(event: MouseEvent) {
    event.stopPropagation();
    onRemove(item);
  }
  return (
    <span className={pillStyles}>
      <span className="text-xs">{item.name}</span>
      <span className={classnames(pillCloseStyles)} onClick={handleClick}>
        {closeIcon}
      </span>
    </span>
  );
}

interface IMultiSelectProps {
  items: Array<Item>;
  autoTargetFirstItem?: boolean;
}

function MultiSelect({ items, autoTargetFirstItem }: IMultiSelectProps) {
  const [selected, setSelected] = useState<Array<Item>>([]);

  function handleSelectOption(item: any, selected: Array<Item>) {
    if (selected.includes(item)) {
      setSelected(selected.filter(selectedItem => selectedItem !== item));
    } else {
      setSelected([...selected, item]);
    }
  }

  function handleRemoveSelectedItem(item: any) {
    setSelected(selected.filter(selectedItem => selectedItem !== item));
  }

  const {
    isOpen,
    decoratedItems,
    getItemProps,
    getListProps,
    getSelectProps,
    isItemActive,
    isItemSelected,
    state
  } = useSelect({
    onSelectOption: handleSelectOption,
    items,
    selected,
    autoTargetFirstItem
  });

  return (
    <div>
      <div
        {...getSelectProps()}
        className={classnames(multiSelectStyles, { "border-blue-600": isOpen })}
      >
        {selected.map(item => (
          <SelectedItem
            key={item.id}
            onRemove={handleRemoveSelectedItem}
            item={item}
          />
        ))}
      </div>
      <ul
        {...getListProps()}
        className={classnames(listBoxStyles, listBoxContainerStyles, {
          hidden: !isOpen
        })}
      >
        {decoratedItems.map((item: DecoratedItem<Item>, index: number) => (
          <li
            {...getItemProps(item)}
            key={item.id || index}
            className={classnames(itemStyles, {
              "bg-gray-200": isItemActive(item, state.context),
              "bg-gray-400": isItemSelected(item, selected)
            })}
          >
            {item.item.name}
          </li>
        ))}
      </ul>
    </div>
  );
}

export default MultiSelect;

// vue-example/src/components/MultiSelect.vue
<template>
  <div>
    <div
      :class="selectClasses"
      @keydown="handleKeydownSelect"
      @click="handleClickSelect"
      tabindex="0"
    >
      <SelectedItem
        v-for="item in state.selected"
        v-bind:key="item.id"
        :item="item"
        :onRemove="handleRemoveSelectedItem"
      />
    </div>
    <ul ref="listRef" :class="listClasses" v-show="isOpen()">
      <li
        v-for="decoratedItem in state.decoratedItems"
        ref="itemsRef"
        :key="decoratedItem.id"
        :class="getItemClasses(decoratedItem)"
        @mousemove="() => handleMousemoveItem(decoratedItem)"
        @click="() => handleClickItem(decoratedItem)"
      >{{ decoratedItem.item.name }}</li>
    </ul>
  </div>
</template>

<script lang="ts">
import SelectedItem from "./SelectedItem.vue";
export const selectStyles =
  "w-64 h-10 border border-gray-500 flex rounded-sm outline-none items-center p-2 focus:border-blue-600 cursor-pointer";
export const listBoxContainerStyles =
  "shadow-lg border border-gray-500 rounded-sm rounded-t-none outline-none absolute bg-white z-10 border-blue-600 cursor-pointer";
export const listBoxStyles = "w-64 h-48 overflow-y-auto cursor-pointer";
export const itemStyles = "px-2 py-1";
import { useMachine } from "@xstate/vue";
import { reactive, ref, onUpdated } from "@vue/composition-api";
import classnames from "classnames";
import {
  selectMachine,
  CLICK_TRIGGER,
  CLICK_ITEM,
  SET_ACTIVE_ITEM,
  KEY_DOWN_SELECT,
  UPDATE_DECORATED_ITEMS,
  UPDATE_LIST_ELEMENT,
  isItemActive,
  isItemSelected
} from "use-dropdown";

type Item = any;

interface IProps {
  items: Array<Item>;
}

export default {
  name: "MultiSelect",
  props: {
    items: Array
  },
  components: {
    SelectedItem
  },
  setup(props: IProps) {
    const itemsRef = ref(null);
    const state = reactive({
      selected: [],
      decoratedItems: props.items.map((item: any) => ({
        ref: null,
        item
      }))
    });

    const listRef = ref(null);

    function handleSelectOption(item: Item) {
      if (state.selected.includes(item)) {
        state.selected = state.selected.filter(
          selectedItem => selectedItem !== item
        );
      } else {
        state.selected = [...state.selected, item];
      }
    }

    const { state: machineState, send } = useMachine(selectMachine, {
      context: {
        listElement: listRef.value as any,
        decoratedItems: state.decoratedItems,
        filteredDecoratedItems: state.decoratedItems,
        onSelectOption: handleSelectOption,
        selected: state.selected
      }
    });

    function getListClasses() {
      return `${listBoxContainerStyles} ${listBoxStyles}`;
    }

    onUpdated(() => {
      if (machineState.value.context.listElement !== listRef.value) {
        send({
          type: UPDATE_LIST_ELEMENT,
          listElement: listRef.value
        });
      }

      const refs = itemsRef?.value || [];
      const decoratedItemsWithRefs = state.decoratedItems.map(
        (item: any, index: number) => ({ ...item, ref: refs && refs[index] })
      );
      if (!machineState.value.context.decoratedItems[0].ref) {
        state.decoratedItems = decoratedItemsWithRefs;
        send({
          type: UPDATE_DECORATED_ITEMS,
          decoratedItems: decoratedItemsWithRefs
        });
      }
    });

    function handleRemoveSelectedItem(item: Item) {
      state.selected = state.selected.filter(
        (selectedItem: Item) => selectedItem !== item
      );
    }

    return {
      state,
      send,
      machineState,
      getListClasses,
      listRef,
      itemsRef,
      handleRemoveSelectedItem
    };
  },
  data: function() {
    return {
      selectClasses: selectStyles,
      listClasses: `${listBoxContainerStyles} ${listBoxStyles}`
    };
  },
  methods: {
    handleKeydownSelect: function(e: KeyboardEvent) {
      this.send({ type: KEY_DOWN_SELECT, e });
    },

    handleClickSelect: function() {
      this.send(CLICK_TRIGGER);
    },

    handleClickItem: function({ item }) {
      this.send({ type: CLICK_ITEM, item });
    },

    handleMousemoveItem: function(decoratedItem) {
      this.send({ type: `${SET_ACTIVE_ITEM}`, decoratedItem });
    },

    isOpen: function() {
      return this.machineState.value === "open";
    },

    getItemClasses: function(decoratedItem) {
      const { context } = this.machineState;
      return classnames(itemStyles, {
        "bg-gray-200": isItemActive(decoratedItem, context),
        "bg-gray-400": isItemSelected(decoratedItem, this.state.selected)
      });
    }
  }
};
</script>
